
%% ==========================================================
%% 系统
%% ==========================================================
% 非法数据...
-define(ERROR_CHECK_SUM,                           8).
% mysql数据库忙
-define(ERROR_BUSY_MYSQL,                          10).
% 心跳太快
-define(ERROR_CHEAT,                               20).
% 参数错误
-define(ERROR_BADARG,                              30).
% 未知错误
-define(ERROR_UNKNOWN,                             40).
% 查询数据超时
-define(ERROR_SELECT_DELAY,                        60).
% 用户名已被注册，请重新输入
-define(ERROR_ROLE_NAME_REPEAT,                    70).
% 用户名太短，请重新输入
-define(ERROR_ROLE_NAME_MIN,                       72).
% 用户名太长，请重新输入
-define(ERROR_ROLE_NAME_LONG,                      74).
% 自己不能调自己base
-define(ERROR_CALL_SELFBASE,                       80).
% 玩家在线，不能读存离线数据
-define(ERROR_ONLINE_READOFFLINE,                  99).
% 验证码错误，请重新输入
-define(ERROR_LOGIN_CHECK,                         101).
% 用户名不存在，请重新输入
-define(ERROR_USER_NOT_EXIST,                      111).
% 该玩家不在线请找其他玩家
-define(ERROR_USER_OFF_LINE,                       112).
% 该玩家在线
-define(ERROR_USER_ON_LINE,                        113).
% 该物品不存在
-define(ERROR_GOODS_NOT_EXIST,                     121).
% 物品数量不足
-define(ERROR_GOODS_LACK,                          122).
% 美刀不足，招财可获得美刀！
-define(ERROR_GOLD_LACK,                           131).
% 美刀不足，招财可获得美刀！
-define(ERROR_GOLD_BIND_LACK,                      132).
% 仓库美刀不足
-define(ERROR_GOLD_DEPOT_LACK,                     133).
% 钻石不足，充值可获得钻石！
-define(ERROR_RMB_LACK,                            134).
% 人物等级不足！
-define(ERROR_LV_LACK,                             136).
% 对方等级不足
-define(ERROR_OTHER_LV_LACK,                       138).
% 对不起，职业不相同
-define(ERROR_DIFFERENT_PRO,                       141).
% 对不起，性别不相同
-define(ERROR_DIFFERENT_SEX,                       142).
% 对不起，属于不同国家
-define(ERROR_DIFFERENT_COUNTRY,                   143).
% 正在战斗中……
-define(ERROR_STATE_ON_WAR,                        151).
% 正在交易中……
-define(ERROR_STATE_ON_BIZ,                        152).
% 正在打造中……
-define(ERROR_STATE_ON_MAKE,                       153).
% 整理仓库中……
-define(ERROR_STATE_ON_DEPOT,                      154).
% 已是组队中的队长
-define(ERROR_STATE_ON_TEAM_LEADER,                159).
% 生命值已满
-define(ERROR_FULL_HP,                             161).
% 能力值已满
-define(ERROR_FULL_MP,                             162).
% 帐户余额不足！
-define(ERROR_CURRENCY_LACK,                       163).
% 背包美刀达到上限,请尽快处理
-define(ERROR_CURRENCY_REACH_MAX,                  164).
% 玩家已死亡
-define(ERROR_STATE_DIE,                           165).
% 当前位置不可使用该物品
-define(ERROR_GOODS_LOCATION_ERROR,                170).
% VIP等级不足，充值可提升VIP等级！
-define(ERROR_VIP_LV_LACK,                         171).
% 该玩家不在线或不存在！
-define(ERROR_NOT_PLAYER,                          172).
% UID不能为空
-define(ERROR_NOT_UID,                             175).
% UUID不能为空
-define(ERROR_NOT_UUID,                            180).
% CID不能为空
-define(ERROR_NOT_CID,                             185).
% SID不能为空
-define(ERROR_NOT_SID,                             188).
% 您已在别处登录
-define(ERROR_OTHER_LOGIN,                         205).
% 您的帐号给冻结24小时
-define(ERROR_OUT_COLD,                            210).
% 您已被禁止登录
-define(ERROR_OUT_IP,                              215).
% 您的帐号已被禁止登录
-define(ERROR_OUT_COLD_LONG,                       220).
% 您的帐号已被GM登录,请15分钟后再登录
-define(ERROR_OUT_GM,                              225).
% 服务器停服维护,请稍后再试
-define(ERROR_OUT_STOP,                            230).
% 角色等级已达到上限
-define(ERROR_ROLE_LV_MAX,                         232).
% 积分不足
-define(ERROR_INTEGRAL_LACK,                       250).
% 充值成功
-define(ERROR_PAY_OK,                              280).

%% ==========================================================
%% 背包
%% ==========================================================
% 背包已满，请尽快清理！
-define(ERROR_BAG_FULL,                            510).
% 背包已满，剩余物品进入临时背包！
-define(ERROR_BAG_FULL_IN,                         520).
% 充值VIP可以扩充背包。
-define(ERROR_BAG_LOCK,                            550).
% 背包容量不足，请尽快清理！
-define(ERROR_BAG_SHORTAGE,                        560).
% 装备未损坏，无需修理
-define(ERROR_BAG_EQUIP_REPAIR_BAN,                570).
% 没有需要修理的装备
-define(ERROR_BAG_EQUIP_NO_REPAIR,                 580).
% 恭喜您！背包已扩充到更大的空间！
-define(ERROR_BAG_OPEN_ALREADY,                    590).
% 仓库美刀存储已达到上限
-define(ERROR_BAG_DEPOT_GOLD_MAX,                  600).
% 仓库美刀单笔存储达到上限
-define(ERROR_BAG_DEPOT_GOLD_ONCE,                 610).
% 仓库空间不足！清尽快清理！
-define(ERROR_BAG_DEPOT_SHORTAGE,                  620).
% 该位置已有物品
-define(ERROR_BAG_GOODS_HAVE,                      630).
% 临时背包已满，无法获得物品
-define(ERROR_BAG_DEPOT_FULL,                      640).
% 次数已达上限
-define(ERROR_BAG_COUNT_MAX,                       650).
% 该物品不可使用
-define(ERROR_BAG_GOODS_USE_BAN,                   660).
% 临时背包无物品
-define(ERROR_BAG_DEPOT_NULL,                      670).
% 物品已过有效期
-define(ERROR_BAG_EXPIRY_OUTDATE,                  680).
% 已镶嵌宝石的装备不可出售
-define(ERROR_BAG_INSET_SELL_BAN,                  690).
% 没有物品要出售
-define(ERROR_BAG_SELL_NULL,                       700).
% 背包已满，无法提取临时背包中的物品！
-define(ERROR_BAG_PICK_BAN,                        710).
% 人物等级不足，无法使用该物品！
-define(ERROR_BAG_LEVEL_SHORTAGE,                  720).
% 坐骑星级不足，无法使用该物品！
-define(ERROR_BAG_STAR_SHORTAGE,                   730).
% 已有该伙伴，无法再邀请！
-define(ERROR_BAG_PARTNER_HAVE,                    740).
% 该物品不能出售！
-define(ERROR_BAG_SELL_BAN,                        750).
% 背包已满，剩余物品进入临时背包！
-define(ERROR_BAG_TEMP_FULL_NOTICE,                760).
% 该物品只能在特定活动期间才可以使用
-define(ERROR_BAG_ACTIVITY_GOODS,                  780).
% 伙伴经验要低于人物等级
-define(ERROR_BAG_USE_EXP_LV,                      800).
% 背包已满，无法进入副本。
-define(ERROR_BAG_FULL_COPY,                       810).
% 背包容量不足，无法打开物品。
-define(ERROR_BAG_RECEIVE,                         820).

%% ==========================================================
%% 好友
%% ==========================================================
% 该玩家已经是你的好友！
-define(ERROR_FRIEND_CONTACT_EXIST,                1030).
% 该玩家不在线或不存在！
-define(ERROR_FRIEND_CONTACT_NULL,                 1040).
% 不能删除最近联系人
-define(ERROR_FRIEND_DEL_RECENT,                   1050).
% 不能添加自己为好友
-define(ERROR_FRIEND_ADD_MYSELF,                   1060).
% 此玩家不存在 
-define(ERROR_FRIEND_NOT_PLAYER,                   1070).
% 没有推荐次数！
-define(ERROR_FRIEND_NO_RECOM_TIMES,               1075).
% 该玩家不是你的好友或已经删除
-define(ERROR_FRIEND_DELETE_FRIEND,                1080).
% 已达到好友人数上限
-define(ERROR_FRIEND_TOPLIMIT,                     1090).

%% ==========================================================
%% 邮件
%% ==========================================================
% 保存箱已满，不能保存信件！
-define(ERROR_MAIL_SAVE_FULL,                      1510).
% 收件人不存在
-define(ERROR_MAIL_RECV_NULL,                      1520).
% 背包已满，无法提取物品！
-define(ERROR_MAIL_PICK_FULL,                      1530).
% 附件物品不存在！
-define(ERROR_MAIL_GOODS_NULL,                     1540).
% 该信件不存在！
-define(ERROR_MAIL_NULL,                           1550).
% 信件已超过有效期！
-define(ERROR_MAIL_NET_TIME,                       1560).
% 信件内容最多300字！
-define(ERROR_MAIL_CONTENT,                        1570).
% 请先领取奖励！
-define(ERROR_MAIL_DELETE_BAN,                     1580).
% 不能邮寄物品
-define(ERROR_MAIL_GOODS,                          1590).
% 不能发信件给自己！
-define(ERROR_MAIL_MINE,                           1600).

%% ==========================================================
%% 交易/寄售
%% ==========================================================
% 距离NPC太远！请靠近点再买卖！
-define(ERROR_BIZ_NPC_FAR,                         2011).
% 该NPC没有此项功能
-define(ERROR_BIZ_ABILITY_NULL,                    2012).
% NPC不存在
-define(ERROR_BIZ_NPC_NULL,                        2013).
% 背包已满，请尽快清理！
-define(ERROR_BIZ_SELF_SHORTAGE,                   2250).
% 对方背包空间不足！
-define(ERROR_BIZ_OTHER_SHORTAGE,                  2260).

%% ==========================================================
%% 组队
%% ==========================================================
% 玩家已有队伍，无法邀请
-define(ERROR_TEAM_HAVE_TEAM,                      2510).
% 对方已经在队伍中
-define(ERROR_TEAM_EXIST,                          2520).
% 该队伍已满员！不能申请入队！
-define(ERROR_TEAM_FULL,                           2530).
% 该队伍不存在！
-define(ERROR_TEAM_NULL,                           2540).
% 对不起，您不是队长！
-define(ERROR_TEAM_NOT_LEADER,                     2570).
% 您不能踢队长离开队伍！
-define(ERROR_TEAM_NOT_KICK_LEADER,                2600).
% 队伍中，不能踢出自己
-define(ERROR_TEAM_NOT_KICK_SELF,                  2610).
% 已有队伍，不能创建新队伍！
-define(ERROR_TEAM_CREATE_HAVE_TEAM,               2645).
% 对不起，您没有队伍！
-define(ERROR_TEAM_NO_TEAM,                        2655).
% 对不起，该队员不存在！
-define(ERROR_TEAM_NO_MEMBER,                      2665).
% 对不起，您已是队长！
-define(ERROR_TEAM_IS_LEADER,                      2705).
% 好友已有队伍！
-define(ERROR_TEAM_IN_TEAM,                        2715).
% 好友等级不足！
-define(ERROR_TEAM_FRIEND_LV_LACK,                 2720).
% 已有队伍，不能加入队伍！
-define(ERROR_TEAM_JOIN_HAVE_TEAM,                 2730).
% 队伍已开始战斗！
-define(ERROR_TEAM_WARING,                         2740).
% 邀请的玩家不存在！
-define(ERROR_TEAM_INVITE,                         2750).
% 没有次数，不能组队！
-define(ERROR_TEAM_NO_TIMES,                       2760).

%% ==========================================================
%% 团队
%% ==========================================================
% 美刀不足！招财可以获得
-define(ERROR_GROUP_MONEY_NOT_ENOUGH,              3010).
% 好友度不足！可通过赠送鲜花获得
-define(ERROR_GROUP_DEGREE_NOT_ENOUGH,             3020).
% 等级不足！
-define(ERROR_GROUP_LEVEL_NOT_ENOUGH,              3030).
% 您无权限修改
-define(ERROR_GROUP_CAN_NOT_MODIFY,                3040).
% 您已经加入团队
-define(ERROR_GROUP_HAD_GROUP,                     3050).
% 该团队拒绝您的请求
-define(ERROR_GROUP_RESERVE_FAIL,                  3110).
% 您还未加入团队
-define(ERROR_GROUP_NOT_JOIN,                      3112).
% 团队人数不足!
-define(ERROR_GROUP_NUMS_NOT_ENOUGT,               3120).
% 团队成员已满
-define(ERROR_GROUP_ADD_MEMBER_FULL,               3130).
% 称号含有非法字符
-define(ERROR_GROUP_CHAR,                          3140).
% 团员不大于3人
-define(ERROR_GROUP_KICK_OUT_FAIL,                 3160).
% 玩家不在线或不存在
-define(ERROR_GROUP_NO_MEMBER,                     3170).

%% ==========================================================
%% 装备栏
%% ==========================================================
% 装备位置不符合
-define(ERROR_EQUIP_POS_WRONG,                     3210).
% 该物品不可装备！
-define(ERROR_EQUIP_NOT_EQUIP,                     3220).
% 装备耐久度过低,请尽快修理！
-define(ERROR_EQUIP_DURABLE_BAD,                   3230).
% 物品已过期
-define(ERROR_EQUIP_EXPIRY_OUTDATE,                3240).
% 性别不符合
-define(ERROR_EQUIP_SEX_NOT,                       3250).
% 人物等级不足，无法装备！
-define(ERROR_EQUIP_LV_NOT,                        3260).
% 人物职业不符，无法装备！
-define(ERROR_EQUIP_PRO_NOT,                       3270).
% 人物品质不足，无法装备！
-define(ERROR_EQUIP_COLOR_LACK,                    3280).

%% ==========================================================
%% 打坐/修炼
%% ==========================================================
% 该区域不可打坐，请移至打坐区域！
-define(ERROR_TRAIN_BAN,                           3710).
% 您已经是打坐状态
-define(ERROR_TRAIN_YET_SINGLE,                    3720).
% 您已经是双修状态
-define(ERROR_TRAIN_YET_DOUBLE,                    3730).
% 对方已经是双修状态，不能邀请
-define(ERROR_TRAIN_HE_YET_DOUBLE,                 3750).
% 对象不能为自己
-define(ERROR_TRAIN_DOUBLE_SELF_BAN,               3760).
% 对方所处场景禁止打坐！
-define(ERROR_TRAIN_HE_MAP_BAN,                    3770).

%% ==========================================================
%% 客栈
%% ==========================================================
% 您没有这个伙伴
-define(ERROR_INN_NO_PARTNER,                      4020).
% 友好度已达上限不能培养
-define(ERROR_INN_NOT_SHINWAKAN,                   4030).
% 声望或友好度不足
-define(ERROR_INN_NOT,                             4040).
% 伙伴携带数已达上限！
-define(ERROR_INN_FULL_PARTNER,                    4050).
% 您携带的伙伴已达到上限
-define(ERROR_INN_RECRUIT_TOPLIMIT,                4060).

%% ==========================================================
%% 称号
%% ==========================================================
% 对不起！您未拥有该称号
-define(ERROR_TITLE_NOT_HAVE,                      4510).
% 已启用了该称号！
-define(ERROR_TITLE_USE_SAMETYPE,                  4520).
% 对不起！你还没启用该称号
-define(ERROR_TITLE_NOT_USE,                       4530).

%% ==========================================================
%% 鲜花
%% ==========================================================
% 对不起！此物品非鲜花不可赠送
-define(ERROR_FLOWER_NOT_FLOWER,                   4730).

%% ==========================================================
%% php服务器
%% ==========================================================
% 请求的超时
-define(ERROR_WEB_TIMEOUT,                         4805).
% 缺少参数(平台商cid)
-define(ERROR_WEB_CID_NOT,                         4810).
% 平台商cid不存在
-define(ERROR_WEB_CID_NOT_EXIST,                   4820).
% 参数验证失败
-define(ERROR_WEB_AUTHENTICATION_FAILE,            4830).
% 缺少参数(服务器sid)
-define(ERROR_WEB_SID_NOT,                         4840).
% 参数有误(cid)
-define(ERROR_WEB_PARAS_CID,                       4850).
% 参数有误(sid)
-define(ERROR_WEB_PARAS_SID,                       4860).
% 缺少参数(验证sign)
-define(ERROR_WEB_AUTH_NOT,                        4870).
% 参数验证失败
-define(ERROR_WEB_AUTH_FAILE,                      4880).
% 密码错误！
-define(ERROR_WEB_LOGIN_PASSWD_ERROR,              4890).
% 机器码有误
-define(ERROR_WEB_LOGIN_MAC_ERROR,                 4900).
% 系统忙,请稍后重试
-define(ERROR_WEB_LOGIN_SYS_ERROR,                 4910).
% 请输入帐号！
-define(ERROR_WEB_REG_ACCOUNT_NOT,                 4920).
% 请输入密码！
-define(ERROR_WEB_REG_PWD_NOT,                     4930).
% 该帐号已存在！
-define(ERROR_WEB_REG_ACCOUNT_EXIST,               4940).
% 不能快速登录请输录帐号密码登录
-define(ERROR_WEB_LOGIN_FAST_ERROR,                4950).
% 登录参数有误
-define(ERROR_WEB_LOGIN_PARAS_ERROR,               4960).
% 机器码不能为空
-define(ERROR_WEB_REG_MAC_NOT,                     4970).
% 帐号不存在(无效操作)
-define(ERROR_WEB_ACCOUNT_EXIST_NOT,               4980).
% 你的游戏版本过低请升级
-define(ERROR_WEB_VERSIONS_LOW,                    4985).
% 帐号UUID不能为空
-define(ERROR_WEB_UUID_EXIST_NOT,                  4990).
% 帐号UID不能为空
-define(ERROR_WEB_UID_EXIST_NOT,                   4995).
% 身份证帐号不能为空
-define(ERROR_WEB_CARD_EXIST_NOT,                  5000).
% 身份证帐号不正确
-define(ERROR_WEB_CARD_ERROR,                      5010).
% 真实姓名不能为空
-define(ERROR_WEB_NAME_EXIST_NOT,                  5020).
% 请求的用户属性字段不能为空
-define(ERROR_WEB_API_FIELD_NULL,                  5160).
% 请求的用户属性字段有误
-define(ERROR_WEB_API_FIELD_ERROR,                 5170).
% 获取用户信息失败
-define(ERROR_WEB_API_FIELD_FAIL,                  5180).
% 钻石数不能小于1
-define(ERROR_WEB_PAY_EMPTY,                       5210).
% 帐号当前服未激活或帐号不存在
-define(ERROR_WEB_PAY_ROLE_NOTFIND,                5215).
% 绑定金元不能大于所充金元数量
-define(ERROR_WEB_PAY_BINDRMB_MAX,                 5220).
% 系统忙!游戏充值失败(db)
-define(ERROR_WEB_PAY_BUSY,                        5230).
% 订单OID不能为空
-define(ERROR_WEB_PAY_OID_EM,                      5235).
% 订单数据异常，充值对象和之前的不一致，需人工处理。
-define(ERROR_WEB_PAY_DATA_UNUSUAL,                5260).
% 补单时订单数据异常，充值额度和之前的不一致，需人工处理。
-define(ERROR_WEB_PAY_REPAIR_ORDER,                5270).
% 排行类型未定义。
-define(ERROR_WEB_TOP_TYPE_ERROR,                  5290).

%% ==========================================================
%% 任务
%% ==========================================================
% 任务不可接
-define(ERROR_TASK_NOT_RECEIVE,                    5310).
% 答案错误！
-define(ERROR_TASK_WRONG_ANSWER,                   5320).
% 任务不存在
-define(ERROR_TASK_NOT_EXIST,                      5330).
% 任务不可放弃
-define(ERROR_TASK_NOT_ABANDON,                    5340).
% 任务未完成
-define(ERROR_TASK_UNFINISHED,                     5350).
% 距离npc太远
-define(ERROR_TASK_DISTANCE_LONG,                  5360).

%% ==========================================================
%% 战斗
%% ==========================================================
% 对不起！无法与自己PK
-define(ERROR_WAR_PK_SELF,                         5810).
% 战斗目标不可以为0
-define(ERROR_WAR_TAGET_NULL,                      5820).
% 您不在本场景内！
-define(ERROR_WAR_NOT_HERE_YOU,                    5830).
% 对方不在场景内！
-define(ERROR_WAR_NOT_HER_FOE,                     5840).
% 距离太远！请靠近
-define(ERROR_WAR_DISTANCE_LONG,                   5850).
% 地图上怪物不存在或已消灭
-define(ERROR_WAR_NOT_HER_MONSTER,                 5860).
% 对不起！您等级低于40级
-define(ERROR_WAR_NOT_PK_LV_LESS,                  5870).
% 本地图不可PK
-define(ERROR_WAR_NOT_PK_SAFE,                     5880).
% 本地图不可PK
-define(ERROR_WAR_NOT_PK_SAFE_WIND,                5890).
% 本地图不可PK
-define(ERROR_WAR_NOT_PK_SAFE_FIRE,                5900).
% 本地图不可PK
-define(ERROR_WAR_NOT_PK_SAFE_CLOUD,               5910).
% 对不起！对方等级低于40级
-define(ERROR_WAR_NOT_PK_LV_LESS_TO,               5920).
% 敌国不可切磋
-define(ERROR_WAR_NOT_PK2_FOE_COUNTRY,             5930).
% 对不起！您在组队中不可切磋
-define(ERROR_WAR_NOT_PK2_TEAM_ME,                 5940).
% 对不起！对方在组队中不可切磋
-define(ERROR_WAR_NOT_PK2_TEAM_TO,                 5950).
% 对不起！副本中不可PK或切磋
-define(ERROR_WAR_NOT_PK_COPY,                     5980).
% 对不起！同一队伍中不可PK或切磋
-define(ERROR_WAR_NOT_PK_TEAM,                     5990).
% 该怪物不可攻击
-define(ERROR_WAR_NOT_ATTACK,                      6000).

%% ==========================================================
%% 签到
%% ==========================================================
% VIP等级不足，充值可提升VIP等级！
-define(ERROR_SIGN_VIP_LOW,                        6310).
% 今日已完成签到！
-define(ERROR_SIGN_RESIGN,                         6320).
% 该功能暂未开放！
-define(ERROR_SIGN_BEGIN_NO,                       6330).
% 错误天数
-define(ERROR_SIGN_DAY,                            6340).

%% ==========================================================
%% 师徒
%% ==========================================================

%% ==========================================================
%% 布阵
%% ==========================================================
% 没有这个伙伴
-define(ERROR_ARRAY_NOT_PARTNER,                   6910).
% 当前阵位已满员，无法上阵！
-define(ERROR_ARRAY_FULL_IDX,                      6920).
% 主角不能下阵！
-define(ERROR_ARRAY_NOT_PLAYER,                    6930).
% 阵位不同，放置错误
-define(ERROR_ARRAY_NOT_POSITION,                  6940).
% 没有交换信息
-define(ERROR_ARRAY_NOT_DATA,                      6950).
% 上阵人数已满，无法上阵！
-define(ERROR_ARRAY_FULL_COUNT,                    6960).
% 主角未到50级,不能交换位置
-define(ERROR_ARRAY_NOT_EXCHANGE,                  6970).

%% ==========================================================
%% 恶魔果实
%% ==========================================================
% 背包已满！商店可出售无用物品
-define(ERROR_FRUIT_SPACE_FULL,                    7030).

%% ==========================================================
%% 装备打造
%% ==========================================================
% 该装备已升至最高等级！
-define(ERROR_MAKE_UPSTEPS_MAX,                    7660).
% 该装备超过洗炼等级！
-define(ERROR_MAKE_BIPTIZE_LV_EXCEED,              7680).
% 该装备未达到洗炼等级！
-define(ERROR_MAKE_BIPTIZE_LV_LACK,                7690).
% 此装备宝石镶嵌已满！
-define(ERROR_MAKE_FULL_SLOT,                      7700).
% 装备升阶后不能超过玩家等级
-define(ERROR_MAKE_LV_LACK,                        7750).
% 不可分解
-define(ERROR_MAKE_PART_BAN,                       7760).
% 不可打造
-define(ERROR_MAKE_MAKE_BAN,                       7770).
% 不可强化
-define(ERROR_MAKE_STREN_BAN,                      7780).
% 不可升阶
-define(ERROR_MAKE_UPGRADE_BAN,                    7790).
% 不可洗练
-define(ERROR_MAKE_WASH_BAN,                       7800).
% 宝石不可合成
-define(ERROR_MAKE_COMPOSE_BAN,                    7810).
% 没有可以合成的宝石！
-define(ERROR_MAKE_COMPOSE_NULL,                   7820).
% 无镶嵌插槽
-define(ERROR_MAKE_INET_NULL,                      7830).
% 所选物品不可镶嵌
-define(ERROR_MAKE_INSET_BAN,                      7840).
% 无此类型宝石
-define(ERROR_MAKE_PEARL_NULL,                     7850).
% 不可拆除
-define(ERROR_MAKE_TAKE_BAN,                       7860).
% 洗练已达到上限
-define(ERROR_MAKE_WASH_MAX,                       7870).

%% ==========================================================
%% 坐骑
%% ==========================================================
% 对不起！此地图禁止骑乘！
-define(ERROR_MOUNT_BAN,                           8005).
% 对不起，您还没有坐骑！
-define(ERROR_MOUNT_HAVE_NOT,                      8010).
% 坐骑已满10星，请先升阶！
-define(ERROR_MOUNT_FULL_STAR,                     8015).
% 美刀不足，无法培养！
-define(ERROR_MOUNT_GOLD_LACK,                     8020).
% 钻石不足，无法培养！
-define(ERROR_MOUNT_RMB_LACK,                      8025).
% 坐骑不存在！
-define(ERROR_MOUNT_NOT_MOUNT,                     8030).
% 未达到坐骑等级要求
-define(ERROR_MOUNT_LACK_LV,                       8035).
% 不能开启新坐骑！
-define(ERROR_MOUNT_LACK_MOUNT,                    8040).
% 坐骑还未开启！
-define(ERROR_MOUNT_NOT_OPEN,                      8045).
% 不能开启下阶坐骑！
-define(ERROR_MOUNT_LACK_LIUSION,                  8050).
% 坐骑还未幻化！
-define(ERROR_MOUNT_NOT_LIUSION,                   8060).
% 道具不足，无法培养！
-define(ERROR_MOUNT_PROP_LACK,                     8065).
% 坐骑未达到仙果等级要求！
-define(ERROR_MOUNT_LACK_PROP,                     8070).
% 坐骑未满10星，不能升阶！
-define(ERROR_MOUNT_NOT_FULL,                      8075).
% 已有默认坐骑！
-define(ERROR_MOUNT_HAVE_DEFAULT,                  8080).

%% ==========================================================
%% 技能
%% ==========================================================
% 星魂值不足，无法激活！
-define(ERROR_SKILL_NO_STAR_VALUE,                 8105).
% 对不起，您还不能激活此星宿！
-define(ERROR_SKILL_NO_STAR_LV,                    8110).
% 前置技能等级不足！
-define(ERROR_SKILL_FRONT,                         8115).
% 装备技能相同位置
-define(ERROR_SKILL_SAME,                          8120).
% 此技能不能学习！
-define(ERROR_SKILL_LEARN,                         8125).
% 对不起！您的生命值不足！
-define(ERROR_SKILL_HP,                            8165).
% 职业或性别错误
-define(ERROR_SKILL_PRO_SEX,                       8180).
% 技能ID错误
-define(ERROR_SKILL_SKILL_ID,                      8185).
% 技能等级错误或已经达到最高等级
-define(ERROR_SKILL_SKILL_LV,                      8186).
% 您已学会此技能
-define(ERROR_SKILL_YES_LEARN,                     8190).
% 技能学习失败
-define(ERROR_SKILL_RESET_OK,                      8200).
% 技能学习金钱不足
-define(ERROR_SKILL_GOLD_NOT_ENGOUH,               8201).
% 技能学习经验不足
-define(ERROR_SKILL_EXP_NOT_ENGOUH,                8202).
% 技能学习战功不足
-define(ERROR_SKILL_POWER_NOT_ENOUGH,              8203).
% 人物等级不足
-define(ERROR_SKILL_NOT_LV,                        8204).
% 该伙伴没有技能
-define(ERROR_SKILL_NOT_EXIT,                      8205).
% 伙伴等级不足
-define(ERROR_SKILL_NOT_PARTENTLV,                 8206).
% 技能已经达到等级上限
-define(ERROR_SKILL_NOT_LIMIT,                     8207).
% 没有这个技能
-define(ERROR_SKILL_NOT_HAVE,                      8208).

%% ==========================================================
%% 采集
%% ==========================================================

%% ==========================================================
%% 变身
%% ==========================================================
% 现在不能重新抽牌
-define(ERROR_POKER_REFRESH_BAN,                   9150).

%% ==========================================================
%% 商城
%% ==========================================================
% 此商品已过期
-define(ERROR_MALL_OUT_TIME,                       9360).
% 已经购买过了
-define(ERROR_MALL_BUY_HAVE,                       9370).
% 本日购买次数达到上限
-define(ERROR_MALL_MAX_PERSON,                     9380).
% 该物品本日已售罄，明日请早。
-define(ERROR_MALL_MAX_GLOBAL,                     9390).
% 非开放日期
-define(ERROR_MALL_DATE_CLOSE,                     9400).
% 不能购买数量为0的物品
-define(ERROR_MALL_NOT_EQUAL,                      9500).

%% ==========================================================
%% 养成
%% ==========================================================
% 等级不符合养成要求
-define(ERROR_CULTIVATE_LV,                        9410).
% 对不起！您还没开始养成
-define(ERROR_CULTIVATE_NOT_START,                 9420).

%% ==========================================================
%% 暗器
%% ==========================================================
% 等级不足！不能激活
-define(ERROR_DARK_HIDEACTIVE,                     9950).

%% ==========================================================
%% 阵营
%% ==========================================================
% 已加入该阵营
-define(ERROR_COUNTRY_JOIN_ALREADY,                10410).
% 已加入阵营
-define(ERROR_COUNTRY_OWN_ALREADY,                 10420).
% 辞去阵营职务，才能转换阵营
-define(ERROR_COUNTRY_CHANGE_OWN_POST,             10430).
% 对不起！您权限不足
-define(ERROR_COUNTRY_NO_PERMISSION,               10440).
% 玩家还没加入阵营
-define(ERROR_COUNTRY_JOIN_NOT_YET,                10450).
% 玩家已有职位
-define(ERROR_COUNTRY_POST_OWN_ALREADY,            10460).
% 玩家不属于本阵营
-define(ERROR_COUNTRY_NOT_SAME,                    10470).
% 对不起！无空缺职位
-define(ERROR_COUNTRY_POST_ALREADY_HAVE,           10480).
% 您查找的玩家不存在！
-define(ERROR_COUNTRY_POST_CHECK_NULL,             10490).
% 对不起，您没有职位
-define(ERROR_COUNTRY_POST_HAVE_NO,                10500).
% 对不起，您还未做阵营任务
-define(ERROR_COUNTRY_TASK,                        10510).

%% ==========================================================
%% 场景
%% ==========================================================
% 等级不足！请努力提升等级
-define(ERROR_SCENES_LV_LACK,                      10710).
% 该地图不存在
-define(ERROR_SCENES_MAP_NULL,                     10720).
% 您不是队长！不能进入场景
-define(ERROR_SCENES_NOT_LEADER,                   10730).
% 非城镇地图不能进入城镇！
-define(ERROR_SCENES_TYPE_ERROR,                   10760).

%% ==========================================================
%% 福利
%% ==========================================================
% 该福利已领取
-define(ERROR_WELFARE_REWARD_FALSE,                11210).
% 对不起！您未达到领取条件
-define(ERROR_WELFARE_REWARD_CONDITION,            11220).
% 充值额度未达到要求
-define(ERROR_WELFARE_REWARD_LIMIT_LACK,           11230).

%% ==========================================================
%% 帮派
%% ==========================================================
% 对不起，您已有社团！
-define(ERROR_CLAN_HAVE_CLAN,                      11510).
% 申请已满
-define(ERROR_CLAN_APPLY_FULL,                     11511).
% 申请已提交！请耐心等待
-define(ERROR_CLAN_APPLY_ALREADY,                  11512).
% 社团人数已满！
-define(ERROR_CLAN_MEMBERS_FULL,                   11513).
% 已在社团中
-define(ERROR_CLAN_EXIST,                          11514).
% 对不起，您没有社团
-define(ERROR_CLAN_NULL1,                          11515).
% 对不起，您不是社团官员
-define(ERROR_CLAN_NOT_OFFICIAL,                   11516).
% 社团邀请已发送
-define(ERROR_CLAN_INVITE_ALREADY,                 11517).
% 该玩家不在社团中
-define(ERROR_CLAN_NOT_EXIST,                      11518).
% 对不起，您不是社长
-define(ERROR_CLAN_NOT_SHAIKH,                     11519).
% 该职位人数已满！
-define(ERROR_CLAN_POST_FULL,                      11520).
% 对不起，您没有此权限
-define(ERROR_CLAN_NOT_POWER,                      11521).
% 属于不同社团
-define(ERROR_CLAN_DIFFERENT,                      11522).
% 对不起，您不能将自己踢出社团
-define(ERROR_CLAN_NOT_KICK_SELF,                  11523).
% 申请者不存在
-define(ERROR_CLAN_APPLY_EXIST,                    11524).
% 此名称已存在
-define(ERROR_CLAN_NAME_EXIST,                     11525).
% 社团不存在
-define(ERROR_CLAN_NO_EXIT,                        11526).
% 社长不能退出社团
-define(ERROR_CLAN_OUT_BAN_M,                      11527).
% 公告字数不能超过40个字
-define(ERROR_CLAN_NOTICE_LENGTH,                  11528).
% 你已经是社长
-define(ERROR_CLAN_MASTER_YET,                     11529).
% 该玩家已加入社团或已撤销申请！
-define(ERROR_CLAN_APPPLY_NULL,                    11530).
% 社团名称太长
-define(ERROR_CLAN_TITLE_MAX,                      11531).
% 距离开上个社团不足一小时
-define(ERROR_CLAN_OUTTIME_MIN,                    11532).
% 社团总数已达上限
-define(ERROR_CLAN_FULL_CLAN,                      11533).
% 你已经报名社团战
-define(ERROR_CLAN_WAR_APPLY_HAVE,                 11534).
% 现在不可报名社团战
-define(ERROR_CLAN_WAR_APPLY_BAN,                  11535).
% 现在不可战斗
-define(ERROR_CLAN_WAR_BAN_NOW,                    11536).
% 你的个人帮派贡献不足！
-define(ERROR_CLAN_NO_STAMINA,                     11537).
% 美刀不足，招财可获得美刀！
-define(ERROR_CLAN_MONEY_LACK,                     11538).
% 社团等级不足！
-define(ERROR_CLAN_LV_LOW,                         11539).
% 对方已死亡
-define(ERROR_CLAN_WAR_HIM_DIE,                    11540).
% 你已经死亡
-define(ERROR_CLAN_WAR_SELF_DIE,                   11541).
% 活动未开启！
-define(ERROR_CLAN_NOT_START,                      11542).
% 活动已结束！
-define(ERROR_CLAN_ACTIVE_END,                     11543).
% 已达活动次数上限
-define(ERROR_CLAN_NO_TIMES,                       11545).
% 摇钱树未升级，无法摇钱！
-define(ERROR_CLAN_YQSNO_UPLV,                     11546).
% 社团战期间,不可进行此操作
-define(ERROR_CLAN_OUT_BAN_WAR,                    11547).
% 同社团不可战斗
-define(ERROR_CLAN_WAR_FRIEND_BAN,                 11548).
% 社团其他成员开启了心魔挑战
-define(ERROR_CLAN_WAR_START_BOSS,                 11549).
% 每天只有两次机会开启帮派BOSS
-define(ERROR_CLAN_NO_COUNT,                       11550).
% 社团等级不足3级！
-define(ERROR_CLAN_CLANBOSS_LV_LOW,                11551).
% 社团等级不足2级！
-define(ERROR_CLAN_CLANCOPY_LV_LOW,                11552).

%% ==========================================================
%% 声望
%% ==========================================================
% 声望等级不足！
-define(ERROR_RENOWN_ENOUGH,                       12010).
% 当前已达到最高等级！
-define(ERROR_RENOWN_MAX,                          12020).
%  已领取过俸禄！
-define(ERROR_RENOWN_FALSE,                        12030).

%% ==========================================================
%% 物品/场景flag
%% ==========================================================
% 此物品不可存仓库
-define(ERROR_FLAG_DEPOT_BAN,                      12510).
% 此物品不可出售商店
-define(ERROR_FLAG_BIZ_SHOP_BAN,                   12520).
% 此物品不可交易
-define(ERROR_FLAG_BIZ_PLAYER_BAN,                 12530).
% 此物品不可销毁
-define(ERROR_FLAG_DESTROY_BAN,                    12540).
% 此物品不可修理
-define(ERROR_FLAG_REPAIR_BAN,                     12550).
% 此物品不可打造
-define(ERROR_FLAG_MAKE_BAN,                       12560).
% 此物品不可装备
-define(ERROR_FLAG_EQUIP_BAN,                      12570).
% 对不起！此场景不可骑乘
-define(ERROR_FLAG_MOUNT_BAN,                      12620).
% 对不起！此场景不可飞入
-define(ERROR_FLAG_FLY_IN_BAN,                     12630).
% 对不起！此场景不可飞出
-define(ERROR_FLAG_FLY_OUT_BAN,                    12640).
% 对不起！此场景禁止修炼
-define(ERROR_FLAG_TRAIN_BAN,                      12660).
% 此场景禁止队伍操作
-define(ERROR_FLAG_TEAM_BAN,                       12670).
% 此场景禁止使用此物品
-define(ERROR_FLAG_GOODS_BAN,                      12680).

%% ==========================================================
%% 荣誉
%% ==========================================================
% 您有荣誉未领取！
-define(ERROR_HONOR_FINISHED,                      13010).
% 已提交
-define(ERROR_HONOR_SUBMIT,                        13020).
% 未完成
-define(ERROR_HONOR_UNFINISHED,                    13030).
% 该项不存在
-define(ERROR_HONOR_ID_NULL,                       13040).

%% ==========================================================
%% 灵兽
%% ==========================================================
% 对不起！宠物不存在
-define(ERROR_PET_NULL,                            13530).
% 宠物栏已满
-define(ERROR_PET_COLUMN_FULL,                     13540).
% 魔宠已至最高等级
-define(ERROR_PET_STEP_MAX,                        13550).
% 宠物已祭炼至神宠
-define(ERROR_PET_REFINE_MAX,                      13560).
% 已召唤此式神或未获得此式神
-define(ERROR_PET_CALL_ERROR,                      13570).
% 人物等级不足
-define(ERROR_PET_LACK_LV,                         13580).
% 魔宠等级不能高于主角的等级
-define(ERROR_PET_PLAYER_LV,                       13590).

%% ==========================================================
%% 副本
%% ==========================================================
% 已经在副本中
-define(ERROR_COPY_IN_ALREADY,                     14010).
% 玩家人数不够
-define(ERROR_COPY_PEOPLE_LACK,                    14020).
% 玩家等级不够
-define(ERROR_COPY_LV_LACK,                        14030).
% 玩家次数已满
-define(ERROR_COPY_COUNT_FULL,                     14040).
% 有队员不符合要求
-define(ERROR_COPY_MEMBER_LACK,                    14050).
% 不是队长
-define(ERROR_COPY_NOT_CAPTAIN,                    14060).
% 对不起,您不在副本中
-define(ERROR_COPY_NOT_IN,                         14070).
% 副本尚未完成
-define(ERROR_COPY_NOT_COMPLETE,                   14080).
% 没有这个副本！
-define(ERROR_COPY_NOT_COPY,                       14100).
% 没有副本数据！
-define(ERROR_COPY_NOT_COPY_DATA,                  14105).
% 这个地图没有副本
-define(ERROR_COPY_MAP_NOT_COPY,                   14110).
% 副本没有场景数据！
-define(ERROR_COPY_NO_SCENE_DATA,                  14115).
% 副本已挂机！
-define(ERROR_COPY_ALREALY_UP,                     14135).
% 副本未通关！
-define(ERROR_COPY_COPY_NOPASS,                    14145).
% 体力不足！
-define(ERROR_COPY_LESS_ENERGY,                    14150).
% 挂机次数已满！
-define(ERROR_COPY_NO_UPCOPY_TIMES,                14160).
% 背包已满，不能进入副本！
-define(ERROR_COPY_BAG_FULL,                       14170).
% 你已经死亡！无法进行该操作。
-define(ERROR_COPY_DIE,                            14180).
% 已领取副本章节评分奖励！
-define(ERROR_COPY_ALREWARD_CHAP,                  14190).
% 章节有副本末达到S评分
-define(ERROR_COPY_CHAP_INALLS,                    14200).

%% ==========================================================
%% 竞技场
%% ==========================================================
% 竞技场未开放或未知错误
-define(ERROR_ARENA_NOT_OPEN,                      14510).
% 数据库没有该挑战信息
-define(ERROR_ARENA_NOT_INFOR,                     14520).
% 没有您需要的步调信息
-define(ERROR_ARENA_NOT_PACE,                      14530).
% 今日购买次数已用完！
-define(ERROR_ARENA_NOT_BUY,                       14540).
% 您挑战次数已用完
-define(ERROR_ARENA_NOT_COUNT,                     14550).
% 正在冷却中……
-define(ERROR_ARENA_NOT_TIME,                      14560).
% 正在竞技场挑战中……
-define(ERROR_ARENA_ARENA_ING,                     14570).
% 等级不足，不能进入竞技场
-define(ERROR_ARENA_NO_ARENA,                      14580).
% 竞技场挑战人数不足
-define(ERROR_ARENA_NO_POE,                        14590).
% 没有该战斗信息
-define(ERROR_ARENA_NOT_MOGO_DATA,                 14600).

%% ==========================================================
%% 排行榜
%% ==========================================================

%% ==========================================================
%% 新手卡
%% ==========================================================
% 对不起！您已领取本类型的活动卡
-define(ERROR_CARD_JION_TYPE,                      15520).
% 对不起！您已领取本活动卡
-define(ERROR_CARD_JION_OK,                        15530).
% 对不起！活动卡已领完
-define(ERROR_CARD_AFIH,                           15540).
% 对不起！此活动卡已被人领取
-define(ERROR_CARD_USED,                           15550).
% 对不起！您已领取过此活动卡
-define(ERROR_CARD_USED_YOU,                       15560).
% 对不起！此活动卡已过期
-define(ERROR_CARD_OUTTIME,                        15565).
% 对不起！此活动未开始
-define(ERROR_CARD_NOT_START,                      15568).
% 对不起！此卡号有误
-define(ERROR_CARD_INVALID,                        15570).
% 对不起，您已经领取了奖励！
-define(ERROR_CARD_HAD_GOTTEN,                     15580).

%% ==========================================================
%% 月度空间(爬塔)
%% ==========================================================

%% ==========================================================
%% 忍者
%% ==========================================================

%% ==========================================================
%% 目标任务
%% ==========================================================
% 奖励不可领取！
-define(ERROR_TARGET_REWARD_BAN,                   17005).
% 任务未完成！
-define(ERROR_TARGET_UNFINISH,                     17010).

%% ==========================================================
%% npc
%% ==========================================================

%% ==========================================================
%% 破军
%% ==========================================================

%% ==========================================================
%% 中忍活动
%% ==========================================================

%% ==========================================================
%% 试炼
%% ==========================================================

%% ==========================================================
%% 财神
%% ==========================================================
% 招财次数不足
-define(ERROR_WEAGOD_NO_TIMES,                     19510).
% 人物等级不足12级
-define(ERROR_WEAGOD_LV_LACK,                      19520).
% vip等级小于6级
-define(ERROR_WEAGOD_NO_ENOUGH_VIP6,               19530).

%% ==========================================================
%% 精力
%% ==========================================================
% 您的体力已不足！
-define(ERROR_ENERGY_LACK,                         20005).
% VIP等级不足，购买次数已达到上限！
-define(ERROR_ENERGY_MAX_TIME,                     20010).
% VIP等级不足，充值可提升VIP等级！
-define(ERROR_ENERGY_VIP_LOW,                      20015).
% 已经领取buff
-define(ERROR_ENERGY_BUFF,                         20020).

%% ==========================================================
%% 店铺
%% ==========================================================
% 对不起，您的美刀不足！
-define(ERROR_SHOP_MOMEY_LACK,                     20505).
% 对不起，您的钻石不足！
-define(ERROR_SHOP_RMB_LACK,                       20506).
% 现在可不是活动时间哦！
-define(ERROR_SHOP_OUT_TIME,                       20510).
% 人物等级不足，请尽快提升！
-define(ERROR_SHOP_LV_LACK,                        20515).
% 非开放时间
-define(ERROR_SHOP_NOT_TIME,                       20520).
% 非开放日期
-define(ERROR_SHOP_NOT_DATE,                       20525).

%% ==========================================================
%% 三界杀
%% ==========================================================
% 今日重置次数已用完！
-define(ERROR_CIRCLE_NOT_RES,                      21010).
% 已挑战
-define(ERROR_CIRCLE_WAR,                          21020).
% 体力不足，无法挑战！
-define(ERROR_CIRCLE_NOT,                          21030).

%% ==========================================================
%% 苦工
%% ==========================================================
% 苦工已达上限，不能抓捕！
-define(ERROR_MOIL_MOIL_FULL,                      21510).
% 今日求救次数已用完！
-define(ERROR_MOIL_RES,                            21520).
% 没有主人
-define(ERROR_MOIL_NOT,                            21530).
% 没这个苦工
-define(ERROR_MOIL_NOT_MOIL,                       21540).
% 今日互动次数已用完！
-define(ERROR_MOIL_ACTIVE,                         21550).
% 今日抓捕次数已用完！
-define(ERROR_MOIL_CAPTRUE,                        21560).
% 您已经拥有此苦工
-define(ERROR_MOIL_USE_MOIL,                       21570).
% 不能抓捕自己的主人！
-define(ERROR_MOIL_NO_HOST,                        21580).
% 互动保护时间内不能进行该操作！
-define(ERROR_MOIL_PROTECT_TIME,                   21590).
% 今日购买次数已用完！
-define(ERROR_MOIL_BUY_LIMIT,                      21600).
% 今日反抗次数已用完！
-define(ERROR_MOIL_PROTEST_NOT,                    21610).
% 今日苦工经验已达上限
-define(ERROR_MOIL_EXP_LIMIT,                      21620).
% 不能向自己的主人求救
-define(ERROR_MOIL_NO_HOST_RES,                    21630).

%% ==========================================================
%% 英雄副本
%% ==========================================================
% 没有这个章节！
-define(ERROR_HERO_NO_CHAP,                        22010).
% 不能购买次数！
-define(ERROR_HERO_NOT_BUY,                        22020).
% 可购买次数不足！
-define(ERROR_HERO_NO_BUY_TIMES,                   22030).

%% ==========================================================
%% 世界boss
%% ==========================================================
% 活动未开始
-define(ERROR_WORLD_BOSS_NOT_START,                22501).
% 请先击杀本阵营BOSS！
-define(ERROR_WORLD_BOSS_NOT_CITY,                 22510).
% 购买次数已达上限！
-define(ERROR_WORLD_BOSS_NOT_LIMIT,                22520).
% 属性加成已达上限！
-define(ERROR_WORLD_BOSS_NOT_ATTR,                 22530).

%% ==========================================================
%% 活动-保卫经书
%% ==========================================================
% 30级才能参加保卫经书活动
-define(ERROR_DEFEND_BOOK_LOW_LV,                  23010).
% 你还未加入阵营，无法参加此活动
-define(ERROR_DEFEND_BOOK_NO_COUNTRY,              23020).
% 所有驻守圈都已入驻满，请稍等~
-define(ERROR_DEFEND_BOOK_TRENCH_FULL_ALL,         23030).
% 活动尚未开启！
-define(ERROR_DEFEND_BOOK_NOT_START,               23040).
% 驻守圈选择错误！
-define(ERROR_DEFEND_BOOK_ERROR_TRENCH,            23050).
% 所选驻守圈已满，请选择其它的驻守圈~
-define(ERROR_DEFEND_BOOK_TRENCH_FULL,             23060).
% 领取BUFF失败，稍后再试~
-define(ERROR_DEFEND_BOOK_GET_BUF_ERROR,           23070).
% 您已在驻守圈内~
-define(ERROR_DEFEND_BOOK_RETRENCH,                23080).
% 怪物被打死了~
-define(ERROR_DEFEND_BOOK_MONSTER_NULL,            23090).
% 击杀奖励已过期~
-define(ERROR_DEFEND_BOOK_ERROR_REWARDS,           23100).

%% ==========================================================
%% VIP
%% ==========================================================
% 当前VIP等级大于体验等级，维持原有VIP等级不变！
-define(ERROR_VIP_NOW_BIG,                         23510).

%% ==========================================================
%% 仙旅奇缘
%% ==========================================================
% 今天次数已用完
-define(ERROR_DICE_COUNT_MAX,                      24010).
% 任务尚未完成
-define(ERROR_DICE_SUBMIT_BAN,                     24020).
% 没有任务可放弃
-define(ERROR_DICE_DROP_NULL,                      24030).
% 已经走到尽头了
-define(ERROR_DICE_STEP_MAX,                       24040).

%% ==========================================================
%% 活动年兽
%% ==========================================================
% 今日3次挑战胜利已经完成,请明天再来
-define(ERROR_NIANSHOU_NOT_COUNT,                  24510).

%% ==========================================================
%% 活动-钓鱼达人
%% ==========================================================
% 正在钓鱼中。。。
-define(ERROR_FISHING_RESTART,                     25010).
% 鱼逃走了！
-define(ERROR_FISHING_FISH_NULL,                   25020).
% 当次钓鱼已结束，请重新开始~
-define(ERROR_FISHING_TIMES_OVER,                  25030).
% 鱼还未上钩~
-define(ERROR_FISHING_NO_FISHS,                    25040).

%% ==========================================================
%% 天宫之战
%% ==========================================================
% 正处于惩罚时间,禁止操作
-define(ERROR_SKYWAR_PUNISH,                       25110).
% 非进行状态
-define(ERROR_SKYWAR_STATE_BAN,                    25120).
% 没有参加资格
-define(ERROR_SKYWAR_LIMIT_BAN,                    25130).
% 你已经死亡
-define(ERROR_SKYWAR_DEAD_ME,                      25140).
% 对方已经死亡
-define(ERROR_SKYWAR_DEAD_HE,                      25150).
% 你没有上阵
-define(ERROR_SKYWAR_READY_ME,                     25160).
% 对方没有上阵
-define(ERROR_SKYWAR_READY_HE,                     25170).
% 同阵营不可战斗
-define(ERROR_SKYWAR_WAR_BAN_SAME,                 25180).
% 只能从城镇进入天宫之战地图
-define(ERROR_SKYWAR_ENTER_ONLY_CITY,              25190).
% 禁止操作
-define(ERROR_SKYWAR_DO_BAN,                       25200).
% boss不存在或已被击杀
-define(ERROR_SKYWAR_BOSS_KILL_HAVE,               25210).

%% ==========================================================
%% 御前科举
%% ==========================================================
% 错误答案
-define(ERROR_KEJU_FALSE,                          25610).
% 已经答题
-define(ERROR_KEJU_FAIL,                           25620).
% 答题时间间隔不够
-define(ERROR_KEJU_PAST,                           25630).
% 现在不是答题时间
-define(ERROR_KEJU_DATAPAST,                       25640).
% 记录不匹配
-define(ERROR_KEJU_ERROR,                          25650).

%% ==========================================================
%% 阵营战
%% ==========================================================
% 参数错误，请重新参战~
-define(ERROR_CAMPWAR_NOT_JOIN,                    26110).
% 未匹配到合适对手，当场决战轮空！
-define(ERROR_CAMPWAR_NO_MATCHS,                   26120).
% 振奋次数已达上限~
-define(ERROR_CAMPWAR_BESTIR_MAX,                  26130).
% 阵营战已经结束
-define(ERROR_CAMPWAR_NOT_START,                   26140).

%% ==========================================================
%% 阎王殿
%% ==========================================================
% 请求伙伴不存在
-define(ERROR_KINGHELL_NOT_PARTNER,                26610).
% 对不起，您还不能激活心经境界
-define(ERROR_KINGHELL_NO_STAR_LV,                 26620).
% 对不起，精魂不足，无法激活
-define(ERROR_KINGHELL_NO_STAR_VALUE,              26630).
% 心经交换失败
-define(ERROR_KINGHELL_NO_XJ_SWAP,                 26650).
% 对不起，获取精魂列表失败
-define(ERROR_KINGHELL_NO_YSNUM,                   26660).
% 对不起，还未有人成功挑战
-define(ERROR_KINGHELL_NO_CHALLENGE,               26680).
% Boss已战胜
-define(ERROR_KINGHELL_CHALLENGE_OK,               26690).
% 对不起，您还不能挑战此Boss
-define(ERROR_KINGHELL_CANT_CHALLENGE,             26700).
% 对不起，您选择的怪物不存在
-define(ERROR_KINGHELL_NO_MONS,                    26710).

%% ==========================================================
%% 跨服战
%% ==========================================================
% 跨服战斗即将开启敬请期待
-define(ERROR_STRIDE_NO_START,                     27110).
% 已报名
-define(ERROR_STRIDE_YES_REPORT,                   27120).
% 数据库繁忙请重新进入
-define(ERROR_STRIDE_NO_DATA,                      27130).
% 今天已许愿
-define(ERROR_STRIDE_WISH,                         27140).

%% ==========================================================
%% 魔王副本
%% ==========================================================
% 没有这个章节！
-define(ERROR_FIEND_NO_CHAP,                       27610).
% 不能刷新副本！
-define(ERROR_FIEND_NOT_FRESH,                     27620).
% 可刷新次数不足!
-define(ERROR_FIEND_NO_FRESH_TIMES,                27630).

%% ==========================================================
%% 珍宝阁系统
%% ==========================================================
% 金钱不足
-define(ERROR_TREASURE_MONEY_NOT_ENCOUGH,          28102).
% 输入错误层数
-define(ERROR_TREASURE_ERROR_ID,                   28103).
% 等级不够，无法进入下一层
-define(ERROR_TREASURE_LV_ENGTHOU,                 28104).
% vip等级不够
-define(ERROR_TREASURE_VIP_NOT_ENOUGH,             28105).
% 合成该宝物的材料不够！
-define(ERROR_TREASURE_MATERIAL,                   28106).
% 不能再次购买
-define(ERROR_TREASURE_NOT_REPEAT_BUY,             28107).
% 打造物品数据出错
-define(ERROR_TREASURE_NOT_GOODS,                  28108).

%% ==========================================================
%% 斗气
%% ==========================================================
% VIP等级不足3级，充值可提升VIP等级！
-define(ERROR_DOUQI_VIP_LIMIT,                     3).
% 请求的伙伴不存在
-define(ERROR_DOUQI_ROLE_ERROR,                    28610).
% 斗气仓库已满，请先吞噬！
-define(ERROR_DOUQI_STORAGE_FULL,                  28620).
% 没有可吞噬的斗气
-define(ERROR_DOUQI_NO_EAT_DOUQI,                  28630).
% 无法装备的斗气
-define(ERROR_DOUQI_UNUSER,                        28640).
% 该功能暂未开放！
-define(ERROR_DOUQI_NOT_START,                     28650).
% 领悟次数已用完！
-define(ERROR_DOUQI_NO_TIMES,                      28660).
% 斗气不存在！
-define(ERROR_DOUQI_NO_DOUQI,                      28670).
% 斗气经验已满
-define(ERROR_DOUQI_FULL_EXP,                      28680).
% 无法吸收比自己品质高的斗气
-define(ERROR_DOUQI_COLOR_LOW,                     28690).
% 已装备了相同类型的斗气！
-define(ERROR_DOUQI_HAVE_OTHER,                    28700).
% 斗魂值不足！
-define(ERROR_DOUQI_ADAM_WAR_LOW,                  28710).
% 该斗气无法分解！
-define(ERROR_DOUQI_NOT_SPLIT,                     28720).
% 已达到该等级可装备个数上限！
-define(ERROR_DOUQI_FULL_EQUIP,                    28730).
% 白色斗气无法拾取！
-define(ERROR_DOUQI_CANT_PICK,                     28740).

%% ==========================================================
%% 日常任务系统
%% ==========================================================
% 领取奖励失败
-define(ERROR_TASK_DAILY_ERROR_REWARD,             29101).
% 任务还没有完成
-define(ERROR_TASK_DAILY_NOT_COMPELETE,            29102).
% vip等级不够
-define(ERROR_TASK_DAILY_VIP_NOT_ENOUGH,           29103).
% 次数已经用完
-define(ERROR_TASK_DAILY_NOT_COUNT,                29104).
% 今天的日常任务已经完成
-define(ERROR_TASK_DAILY_COMPELETE,                29105).

%% ==========================================================
%% 风林山火
%% ==========================================================
% 今天已经没有剩余的活动次数
-define(ERROR_FLSH_NO_TIMES,                       29610).
% 没有牌语数据
-define(ERROR_FLSH_NO_PAI_DATA,                    29620).
% 牌位置错误
-define(ERROR_FLSH_POS_ERROR,                      29630).

%% ==========================================================
%% 每日一箭
%% ==========================================================
% 今天没有射箭次数
-define(ERROR_ARROW_DAILY_NO_TIMES,                30110).

%% ==========================================================
%% 神器
%% ==========================================================
% 没有圣水
-define(ERROR_MAGIC_EQUIP_NO_SHENGSHUI,            30610).
% 神器等级不足
-define(ERROR_MAGIC_EQUIP_LACK_LV,                 30620).

%% ==========================================================
%% 格斗之王
%% ==========================================================
% 人物等级不足
-define(ERROR_WRESTLE_NOT_LV,                      31101).
% 活动暂时未开放
-define(ERROR_WRESTLE_NOT_WRESTLE,                 31102).
% 不能重复报名
-define(ERROR_WRESTLE_REPEAT_APPLY,                31103).
% 活动报名人数太少
-define(ERROR_WRESTLE_COUNT_LESS,                  31104).
% 玩家还没有报名
-define(ERROR_WRESTLE_NOT_APPLY,                   31105).
% 没有参加竞技场
-define(ERROR_WRESTLE_NOT_AREAN,                   31106).
% 没有冠军这个人物
-define(ERROR_WRESTLE_NOT_GUANJUN,                 31107).
% 没有亚军这个人物
-define(ERROR_WRESTLE_NOT_YAJUN,                   31108).
% 争霸赛还没有开始
-define(ERROR_WRESTLE_NOT_ZHENGBA,                 31109).
% 决赛还没有开始
-define(ERROR_WRESTLE_NOT_FINAL,                   31110).
% 预赛已经结束
-define(ERROR_WRESTLE_YUSAI_END,                   31111).

%% ==========================================================
%% 拳皇生涯
%% ==========================================================
% 没有挑战次数
-define(ERROR_FIGHTERS_NO_WARTIMES,                31610).
% 没有购买次数
-define(ERROR_FIGHTERS_NO_BUYTIMES,                31620).
% 没有挂机的副本
-define(ERROR_FIGHTERS_NO_UP_COPY,                 31630).
% 挂机未完成，不能重置
-define(ERROR_FIGHTERS_NO_RESET,                   31640).
% 请先重置
-define(ERROR_FIGHTERS_PLEASE_RESET,               31650).
% 重置次数不足
-define(ERROR_FIGHTERS_NO_RESET_TIMES,             31660).

%% ==========================================================
%% 拳王提示
%% ==========================================================
% 请选中要领取奖励的邮件！
-define(ERROR_KOF_TIPS_SELECT_MAIL_AWARDS,         32101).
% 请选中要删除的邮件！
-define(ERROR_KOF_TIPS_SELECT_MAIL_DELETE,         32102).
% 没有可领取奖励！
-define(ERROR_KOF_TIPS_MAIL_NO_REWARD,             32103).
% 请先领取奖励！
-define(ERROR_KOF_TIPS_MAIL_RECEIVE_AWARDS,        32104).
% 招财次数不足，提升VIP等级可增加次数！
-define(ERROR_KOF_TIPS_FORTUNE_NO_TIMES,           32110).
% 声望不足，竞技场可获得声望！
-define(ERROR_KOF_TIPS_RENOWN_LACK,                32120).
% 可携带伙伴已达上限！
-define(ERROR_KOF_TIPS_PARTNER_CARRY_LIMIT,        32130).
% 可出战伙伴已达上限！
-define(ERROR_KOF_TIPS_PARTNER_PLAY_LIMIT,         32131).
% 强化等级不能高于人物等级！
-define(ERROR_KOF_TIPS_STRENGTHENING_LIMIT,        32140).
% 宝石不足，商场可获得宝石！
-define(ERROR_KOF_TIPS_GEM_LACK,                   32150).
% 合成卷轴不足，商场可获得卷轴！
-define(ERROR_KOF_TIPS_GEM_REEL_LACK,              32151).
% 魔石不足，魔王副本可获得魔石！
-define(ERROR_KOF_TIPS_MAGIC_STONES_LACK,          32160).
% VIP2级以上开通此功能！
-define(ERROR_KOF_TIPS_VIP_LEVEL_LOW,              32170).
% 今天活跃度还是够！
-define(ERROR_KOF_TIPS_LOW_VITALITY,               32180).
% 已经领过该阶段奖励了！
-define(ERROR_KOF_TIPS_REGET,                      32190).
% 功能暂未开放，敬请期待！
-define(ERROR_KOF_TIPS_CLOSE_FUN,                  32200).

%% ==========================================================
%% 新手特权
%% ==========================================================
% 投资理财已经开通
-define(ERROR_PRIVILEGE_REOPEN,                    32610).
% 投资理财未开通
-define(ERROR_PRIVILEGE_NO_OPEN,                   32620).
% 今天奖励已经领取
-define(ERROR_PRIVILEGE_GOT_REWARD,                32630).
